# Generated by Django 4.2 on 2023-05-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="add",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mname", models.CharField(max_length=100)),
                ("mabout", models.CharField(max_length=100)),
                ("mstory", models.CharField(max_length=200)),
                ("mtime", models.TimeField(verbose_name="")),
            ],
        ),
    ]
