# Generated by Django 4.2 on 2023-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="add",
            name="mcharge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
