# Generated by Django 4.2 on 2023-05-04 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0002_add_mcharge"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="add",
            new_name="adds",
        ),
    ]
