# Generated by Django 4.2 on 2023-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0003_rename_add_adds"),
    ]

    operations = [
        migrations.CreateModel(
            name="adde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mname", models.CharField(max_length=100)),
                ("mabout", models.CharField(max_length=100)),
                ("mstory", models.CharField(max_length=200)),
                (
                    "mcharge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mtime", models.TimeField(verbose_name="")),
            ],
        ),
        migrations.DeleteModel(
            name="adds",
        ),
    ]
