# Generated by Django 4.2 on 2023-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0005_reserve"),
    ]

    operations = [
        migrations.CreateModel(
            name="reserves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name1", models.CharField(max_length=100)),
                ("email1", models.EmailField(max_length=254)),
                ("theater", models.CharField(max_length=25)),
                ("showdate", models.DateField()),
                ("time1", models.TimeField(verbose_name="")),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="reserve",
        ),
    ]
