# Generated by Django 4.2 on 2023-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film", "0006_reserves_delete_reserve"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("mess", models.CharField(max_length=200)),
            ],
        ),
    ]
